### ISSUE TITLE
Make the README

### ISSUE THREAD

**Issue by santiagomed** [void-tech-um/mthrift-server#1]
The README should include:

1. Project’s Title
2. Project Description
3. Project Requirements and Dependencies
4. How to Set up and Run the Project
5. How to make use of the Project
6. A License

**Comment by jennweir** [comment]
I updated the README but definitely think I am missing something when it comes to dependencies/setting up the project. I also recognize we can edit this as we go.

**Comment by santiagomed** [comment]
Great start to the README @jennweir! Check out [this](https://x-team.com/blog/how-to-write-a-great-readme) article for README writing guidance. Also, feel free to look at the [Backend Workshop README](https://github.com/void-tech-um/backend-workshop) for a smaller example.
